### PR TITLE
WIP: simple pipeline and cache support

### PR DESCRIPTION
**Pull request by xiang90**
1. add a simple pipeline
2. add a random policy cache

### CODE REVIEW

**Comment by philips** [comment]
What is the cache for. No callers were added.

Pipeline looks fine.

**Comment by philips** [comment]
@xiangli-cmu Should we just merge this or do you want to do more work? It would be an insta-merge for me if that unused cache wasn't there.

**Comment by xiang90** [comment]
@philips do not merge that. i will work on this when i get time.

**Comment by philips** [comment]
Ok, prefixed with WIP (work in progress) so we all know. Thanks.

**Comment by bcwaldon** [comment]
reopen when relevant

**Pull request closed without merging**
